class Strings {
  // static String description="Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s";
  static String forgotPassword = "Şifreni mi unuttun ?";
  static String forgotPassDesc =
      "Lütfen mail adresini gir. Sana, yeni şifre oluşturabileceğin bir link göndereceğiz."; // TODO Çeviri Yapılacak
  static String hintEmail = "E-Posta Adresi"; // TODO Çeviri Yapılacak
  static String hintName = "Ad"; // TODO Çeviri Yapılacak
  static String hintSurname = "Soyad"; // TODO Çeviri Yapılacak
  static String hintPhoneNumber = "Telefon Numarası"; // TODO Çeviri Yapılacak
  static String hintPassword = "Şifre"; // TODO Çeviri Yapılacak
  static String hintConfirmPassword = "Şifre Onayı"; // TODO Çeviri Yapılacak
  static String signUp = "Kayıt Ol";
  static String signIn = "Giriş Yap";
  static String send = "Gönder";
  static String skip = "Geç";
  static String next = "İleri";
  static String prev = "Geri";
  static String getBack = "Geri Dön";
  static String cancel = "Vazgeç";
  static String select = "Seç";
  static String selected = "Seçildi";
  // static String task = "Task";
  // static String taskDes = "Do daily task to gain the integrals";
  // static String darkTheme = "Dark Theme";
  // static String darkThemeDec = "Try new look on dark version";
  // static String treadSetter = "A trendsetter";
  // static String yourProfile = "Your Profile";
  // static String destination = "Choose Your Destination";
  // static String advanture = "Choose Your Destination";
  // static String enjoyTravel = "Enjoy your travel";
  static String getStarted = "Hadi Başlayalım!";
  // static String exploreNature = "Explore the Nature";
  // static String recommended = "Recommended";
  // static String popular = "Popular";
  // static String newDestination = "New Destination";
  // static String hiddenGems = "Hidden Gems";
  // static String popularPlace = "Popular Places";
  // static String discountText = "38% OFF";
  // static String bestHotels = "Best Hotels";
  // static String chooseDate = "Choose date";
  // static String numbersOfRooms = "Number of Rooms";
  // static String hotelFound = "530 hotels found";
  // static String filter = "Filter";
  // static String viewAll = "View All";
  // static String freeWifi = "Free \n Wi-Fi";
  // static String beach = "Sand Beach";
  // static String coastLine = "First Coastline";
  // static String barRestorent = "bar and Resturant";
  // static String description1 = "Descriptions :-";
  // static String otherImage = "Other Images";
  // static String userText = "Hey, Faruk !";
  // static String newWord = "New";
  // static String nearby = "Nearby";
  // static String topDeals = "Top Dealers";
  // static String hiddenDes = "Hidden Gems in your fav places";
  // static String longHiddenDes = "Watch and uncover the best of #MyIndia";
  // static String iceLand = "Nusa Penida Island";
  // static String bali = "Bali, Indonesia";
  // static String privacy = "Privacy";
  // static String address = "Address";
  // static String setting = "Setting";
  
  static String notifications = "Bildirimler";
  static String notificationsDes = "Bildirimlerden haberdar olmak için sık sık kontrol et.";
  static String logout = "Çıkış Yap";
  static String logoutDes = "Sistemden çık.";
  static String editProfile = "Profili Düzenle";
  static String editProfileDes = "Profil bilgilerini güncelle.";
  static String myTickets = "Biletlerim";
  static String myTicketsDes = "Daha önce aldığın biletleri gör.";

  // static String settingDes = "Set up your own information!";
  // static String addressDec = "Complete your individual address";
  // static String privacyDes = "Protect your personal information";
  // static String visitMountain = "visit the mountains";
  // static String gatewayMountains = "Gataway to the Mountains";
  // static String discoverInterest = "Discover by Interest";
  // static String topDestination = "Top Destinations";
  // static String exploreWorld = "Let's Explore\nThe World";
  // static String paymentMethod = "Payment Methods";
  // static String subTotal = "SubTotal";
  // static String discount = "Discounts";
  // static String total = "Total";
  // static String search = "Search";
  // static String longTerm = "Long term and short term";
  // static String availableCars = "Available Cars";
  // static String topDeals1 = "Top Deals";
  // static String addCalender = "Add To Calendar";
  // static String carRental = "Car Rental";
  // static String about = "About";
  // static String readMore = "Read more...";
  // static String organization = "Organizer";
  // static String follow = "Follow";
  // static String price = "Price";
  // static String perPerson = "/per person";
  // static String booked = "Booked";
  // static String success = "Success";
  // static String events = "Events";
  // static String schedule = "Schedule";
  // static String allEvent = "All Events";
  // static String nearbyConcert = "Nearby Concerts";
  // static String upcomingEvent = "Upcoming Events";
  static String bookTrip = "Seferinizi Seçin";
  static String findRoute = "Bir Sefer Ara";
  // static String eTicket = "E-Ticket";
  // static String mySelf = "My Self";
  // static String someone = "Someone";
  static String booking = "Bilet Özeti";
  static String payment = "Ödeme";
  // static String address1 = "Novotel Imagica Khopoli";
  // static String addressLocation = "Sangadevdi , Khopoli";
  // static String hotelPrivacy = "MY Safety - Safe and Hygienic Stays";
  // static String exploreNear = "Let's explore what’s happening nearby";
  // static String bookTicket = "Book a Ticket";
  // static String splashText = "Flutter Travel App \n Template Kit ";
  // static String checkIn = "Check-in:";
  static String arrive = "Varış";
  static String departure = "Kalkış";
  // static String guestRoom = "Guest & Rooms ";
  static String adultsChildren = "Yetişkinler &\nÇocuklar &\nAraçlar";
  // static String hotelAdult = "2 Adults | 1 Room";
  // static String classic = "Classic(2X)";
  static String infoTitle = "Bilgilendirme";
  // static String roomCancel = "Room with Free Cancellation | Breakfast only";
  // static String breakFast = "Free Breakfast";
  static String cancelIn = "Son 6 saate kadar ücretsiz iptal hakkı.";
  static String cancelFees =
      "23 Haziran 11:59' a kadar ücretsiz iptal ettirebilirsiniz.";
  static String ferryPolicy = "Bilet İptali ve İptal Etme Politikaları";
  // static String roomNight = "1 Room x 1 Night";
  static String basePrice = "Temel Fiyat";
  static String tDiscount = "İndirim Miktarı";
  static String priceDiscount = "İndirimli Fiyat";
  static String amountPaid = "Ödenecek Tutar";
  static String serviceFee = "Servis Bedeli";
  // static String bookText = "I am booking for";
  static String bookProcess =
      "By Proceeding, i agree to apps "; // TODO Çeviri Yapılacak
  static String userAgreement =
      "user Agreement, Terms of Service "; // TODO Çeviri Yapılacak
  static String cancelPolicy =
      "Cancellation & Property Booking Policies"; // TODO Çeviri Yapılacak
  static String continueText = "Devam Et";
  static String searchTrip = "Sefer Ara";
  static String oneWay = "Tek Yön";
  static String twoWay = "Gidiş-Dönüş";
  // static String london = "London...";
  // static String hotels = "Hotels";
  // static String fromMumbai = "From Mumbai";
  // static String theme = "Theme";
  // static String weekEndGateways = "Weekend Getaway+1";
  // static String approxTrip = "Approx. for 7 nights trip";
  // static String details = "Details";
  // static String place = "Shrinagar";
  // static String interestLocation = "Paradies on the Banks of Jehlum";
  // static String overView = "Overview:-";
  // static String bestTimeVisit = "Best Time to Visit:-";
  // static String peakPlace = "PEAK SEASON";
  // static String moreCrowd = "More Crowd";
  // static String temp1 = "Temperature between 10°C to 30°C";
  // static String sightSeen = "Sightseeing and the lively festivals";
  // static String modRate = "MODERATE SEASON";
  // static String avgCrowd = "Average Crowd";
  // static String temp2 = "Windly weather with cool tempratures";
  // static String sceneries = "Sightseeing and the beautiful sceneries";
  // static String offSeason = "OFF-SEASON";
  // static String lessCrowd = "Less Crowd";
  // static String temp3 = "Chilly weather with 0°C and 15°C";
  // static String lakes = "Snowfall and visiting the frozen lakes";
  // static String thingsToSee = "Things To See:-";
  // static String bookYourTrip = "Book Your Trip:-";
  // static String travel = "Travel";
  // static String recommended1 = "Recommended";
  // static String train = "Train to Lonavala";
  // static String viewDetails = "VIEW DETAILS";
  // static String otherOption = "Other Option";
  // static String setting1 = "Settings";
  // static String explore = "Explore";
  // static String privacyPolicy = "Privacy Policy";
  // static String interestDummy = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor.Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes";

  // static String detailDes = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut scelerisque arcu quis eros auctor, eu dapibus urna congue. Nunc nisi diam, semper maximus risus dignissim, semper maximus nibh. Sed finibus ipsum eu erat finibus efficitur. ";

}
